artifacts_root: "artifacts"

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing"
  local_data_file: "artifacts/data_ingestion/data.zip"
  unzip_dir: "artifacts/data_ingestion/unzipped_data"

prepare_base_model:
  root_dir: "C:/Users/Swarnendu/Desktop/End-to-end-Chest-Cancer-Classification-using-MLflow-DVC/artifacts/prepare_base_model"
  base_model_path: "C:/Users/Swarnendu/Desktop/End-to-end-Chest-Cancer-Classification-using-MLflow-DVC/artifacts/prepare_base_model/base_model.h5"
  updated_base_model_path: "C:/Users/Swarnendu/Desktop/End-to-end-Chest-Cancer-Classification-using-MLflow-DVC/artifacts/prepare_base_model/base_model_updated.h5"

training:
  root_dir: "C:/Users/Swarnendu/Desktop/End-to-end-Chest-Cancer-Classification-using-MLflow-DVC/artifacts/training"
  trained_model_path: "C:/Users/Swarnendu/Desktop/End-to-end-Chest-Cancer-Classification-using-MLflow-DVC/artifacts/training/model.h5"
